CREATE TABLE IF NOT EXISTS form_1099_b (
  id SERIAL PRIMARY KEY,
  return_id INTEGER REFERENCES returns(id) ON DELETE CASCADE,
  description VARCHAR(255) NOT NULL,
  proceeds DECIMAL(15, 2) NOT NULL DEFAULT 0,
  cost_basis DECIMAL(15, 2) NOT NULL DEFAULT 0,
  is_long_term BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
